### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 500
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 500
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "8e256b8ea3254c3a9ab0866ca0f5f8f6",
  "accountNumber": "1000000000",
  "amount": 500
}

### query transaction
GET http://localhost:8080/transaction/8e256b8ea3254c3a9ab0866ca0f5f8f6
