### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "9202474406",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "9202474406",
  "amount": 500
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "34f1fb05c27b4b558d4978148c768813",
  "accountNumber": "9202474406",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/0fdfe719c9e74dc8bd843105b4fd0b2d
